language: node_js
node_js:
 - "stable"
cache:
  directories:
  - node_modules
  - '$HOME/.npm'
install:
  - npm install
  - npm install -g lerna
script:
  - npm run bootstrap
  - npm run build
  - npm run test
  - npm run lint
